//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBridge_Admin_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string TITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public string CATEGORY { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string IMAGEURL { get; set; }
        public Nullable<int> AVAILABLEUNITS { get; set; }
    }
}
